### ISSUE TITLE
I get the following errors

### ISSUE THREAD

**Issue by PocketCoder** [sketchytech/FileSave#2]
Errors: 

![Errors](https://cloud.githubusercontent.com/assets/3524257/5693963/15b85960-9930-11e4-9fbe-4211f31eb033.png)

**Comment by scazy0rg** [comment]
for each error:

1) var libraryDirectory:String!
2) return NSURL(string: libraryDirectory)!

**Comment by sketchytech** [comment]
Update should fix these errors.
